<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Video\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BunLabs.NAudio.Flac" Version="2.0.1" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="1.0.0-beta13" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LAWS.Voices.Shared\LAWS.Voices.Shared.csproj" />
  </ItemGroup>

</Project>
