<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>LAWS.Voices.favicon.ico</ApplicationIcon>
    <PackageIcon>LAWS.Voices.favicon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="LAWS.Voices.favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LAWS.Voices.Shared\LAWS.Voices.favicon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LAWS.Voices.Cuda13\LAWS.Voices.Cuda13.csproj" />
    <ProjectReference Include="..\LAWS.Voices.Multimodal\LAWS.Voices.Multimodal.csproj" />
    <ProjectReference Include="..\LAWS.Voices.Shared\LAWS.Voices.Shared.csproj" />
    <ProjectReference Include="..\LAWS.Voices.OpenVino\LAWS.Voices.OpenVino.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>