<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ElBruno.LocalEmbeddings.Npu.Intel" Version="1.5.0" />
		<PackageReference Include="JYPPX.OpenVINO.CSharp.API" Version="3.2.2" />
		<PackageReference Include="JYPPX.TensorRT.CSharp.API.runtime.win-x64.cuda12" Version="0.0.5" NoWarn="NU1701" />
		<PackageReference Include="OpenVINO.runtime.win" Version="2026.1.0" NoWarn="NU1701" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LAWS.Voices.Downloader\LAWS.Voices.Downloader.csproj" />
	  <ProjectReference Include="..\LAWS.Voices.Multimodal\LAWS.Voices.Multimodal.csproj" />
	  <ProjectReference Include="..\LAWS.Voices.Shared\LAWS.Voices.Shared.csproj" />
	</ItemGroup>

</Project>